services:
  rms_auth_postgres:
    image: postgres:latest
    container_name: rms_auth_postgres
    environment:
      POSTGRES_DB: rms_auth_db
      POSTGRES_USER: rms_auth_user
      POSTGRES_PASSWORD: rms_auth_password
    ports:
      - "7000:5432"
    volumes:
      - rms_auth_postgres_data:/var/lib/postgresql/data
    networks:
      - rms_auth_postgres_network

  rms_auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rms_auth_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rms_auth_postgres:5432/rms_auth_db
      SPRING_DATASOURCE_USERNAME: rms_auth_user
      SPRING_DATASOURCE_PASSWORD: rms_auth_password
      JWT_SECRET: 107fc1bde509f3151f72f828c40001c9df1fde518a5d85972540dcd93a57118b
      JWT_EXPIRATION: 360000
    ports:
      - "5000:5000"
    depends_on:
      - rms_auth_postgres
    networks:
      - rms_auth_postgres_network

networks:
  rms_auth_postgres_network:

volumes:
  rms_auth_postgres_data:
